/**
 * Curated list of important GitHub repositories.
 * Same structure as the GitHub API response so portfolio.jsx needs no changes.
 * Update this file to add/remove/reorder projects.
 */
const projects = [
	{
		name: "glpwnme",
		description: "GLPI vulnerability assessment tool — automated detection of known CVEs and misconfigurations in GLPI instances.",
		language: "Python",
		html_url: "https://github.com/bengo237/glpwnme",
		homepage: null,
		topics: ["pentesting", "security"],
		created_at: "2025-03-25T11:56:41Z",
		svn_url: "https://github.com/bengo237/glpwnme",
	},
	{
		name: "wazuh-kubernetes",
		description: "Production-ready Wazuh SIEM deployment on Kubernetes with AWS integration.",
		language: "Shell",
		html_url: "https://github.com/bengo237/wazuh-kubernetes",
		homepage: "https://github.com/bengo237/wazuh-kubernetes",
		topics: ["aws", "kubernetes-cluster", "wazuh"],
		created_at: "2024-02-26T09:26:10Z",
		svn_url: "https://github.com/bengo237/wazuh-kubernetes",
	},
	{
		name: "CipherBuster",
		description: "RSA vulnerability analysis tool with automated attack techniques — Wiener, Fermat, common modulus and more.",
		language: "Python",
		html_url: "https://github.com/bengo237/CipherBuster",
		homepage: null,
		topics: ["pentesting", "security"],
		created_at: "2024-07-29T07:43:31Z",
		svn_url: "https://github.com/bengo237/CipherBuster",
	},
	{
		name: "risqueNumeriqueSI",
		description: "Cybersecurity risk management framework — PSSI, EBIOS RM, ISO 27001/27005 and regulatory compliance resources.",
		language: null,
		html_url: "https://github.com/bengo237/risqueNumeriqueSI",
		homepage: null,
		topics: ["security"],
		created_at: "2024-12-02T14:11:51Z",
		svn_url: "https://github.com/bengo237/risqueNumeriqueSI",
	},
	{
		name: "SNORT-GUI",
		description: "Blue team companion GUI for Snort IDS — real-time alert visualization and rule management.",
		language: "JavaScript",
		html_url: "https://github.com/bengo237/SNORT-GUI",
		homepage: "https://whitehatcyberus.github.io/SNORT-GUI/",
		topics: ["security"],
		created_at: "2024-09-05T12:26:40Z",
		svn_url: "https://github.com/bengo237/SNORT-GUI",
	},
	{
		name: "wazuh-agent-status",
		description: "Go application to monitor and report the real-time status of Wazuh agents across the infrastructure.",
		language: "Go",
		html_url: "https://github.com/bengo237/wazuh-agent-status",
		homepage: null,
		topics: ["security"],
		created_at: "2024-08-19T11:45:28Z",
		svn_url: "https://github.com/bengo237/wazuh-agent-status",
	},
	{
		name: "snort-docker",
		description: "Dockerized Snort3 deployment for Network Functions Virtualization — plug-and-play network intrusion prevention.",
		language: "Dockerfile",
		html_url: "https://github.com/bengo237/snort-docker",
		homepage: null,
		topics: ["docker", "snort-rules", "snort3"],
		created_at: "2024-03-20T16:35:54Z",
		svn_url: "https://github.com/bengo237/snort-docker",
	},
	{
		name: "keycloak-traefik-letsencrypt-docker-compose",
		description: "Keycloak IAM with Traefik reverse proxy and Let's Encrypt TLS — full zero-trust identity stack via Docker Compose.",
		language: "Shell",
		html_url: "https://github.com/bengo237/keycloak-traefik-letsencrypt-docker-compose",
		homepage: null,
		topics: ["docker", "security"],
		created_at: "2024-02-29T11:21:43Z",
		svn_url: "https://github.com/bengo237/keycloak-traefik-letsencrypt-docker-compose",
	},
	{
		name: "dylane",
		description: "Personal cybersecurity portfolio built with Next.js and React — showcasing projects, certifications and expertise.",
		language: "JavaScript",
		html_url: "https://github.com/bengo237/dylane",
		homepage: "https://dylane-mu.vercel.app/",
		topics: ["cyber-security", "javascript", "nextjs", "portfolio-website", "react"],
		created_at: "2024-05-11T22:39:47Z",
		svn_url: "https://github.com/bengo237/dylane",
	},
];

export default projects;
