name: OWASP ZAP Scan

on:
    pull_request:
        branches: [master]

jobs:
    zap_scan:
        runs-on: ubuntu-latest
        name: Scan the web application
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  ref: report

            - name: ZAP Scan
              uses: zaproxy/action-baseline@master
              with:
                  docker_name: "ghcr.io/zaproxy/zaproxy:stable"
                  target: "https://dylane-mu.vercel.app/"
                  rules_file_name: ".zap/rules.tsv"
                  cmd_options: "-J report.json"

            - name: Run Wazuh Agent Installation Script
              run: sudo bash ./install_wazuh_agent.sh
              env:
                  GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
