name: OWASP ZAP Scan

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    zap_scan:
        runs-on: ubuntu-latest
        name: Scan the web application
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  ref: master

            - name: ZAP Scan
              id: zap_scan
              uses: zaproxy/action-baseline@master
              with:
                  docker_name: "ghcr.io/zaproxy/zaproxy:stable"
                  target: "https://dylane-mu.vercel.app/"
                  rules_file_name: ".zap/rules.tsv"
                  cmd_options: "-J report.json"

            - name: Save ZAP Report
              uses: actions/upload-artifact@v2
              with:
                  name: zap-report
                  path: report.json

            - name: Download ZAP Report
              uses: actions/download-artifact@v2
              with:
                  name: zap-report
                  path: ./zap_report

            - name: Commit and Push ZAP Report
              run: |
                  git config --global user.name 'Dylane Bengono'
                  git config --global user.email 'chaneldylanebengono@gmail.com'
                  git add ./zap_report/report.json
                  git commit -m 'Add ZAP report'
                  git push
              env:
                  GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
