name: OWASP ZAP Scan

on:
    pull_request:
        branches: [master]

jobs:
    zap_scan:
        runs-on: ubuntu-latest
        name: Scan the web application
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  ref: report
            - name: ZAP Scan
              uses: zaproxy/action-baseline@master
              with:
                  docker_name: "ghcr.io/zaproxy/zaproxy:stable"
                  target: "https://dylane-mu.vercel.app/"
                  rules_file_name: ".zap/rules.tsv"
                  cmd_options: "-J report.json"
            - name: Save ZAP Report
              uses: actions/upload-artifact@v2
              with:
                  name: zap-report
                  path: report.json
            - name: Download ZAP Report
              uses: actions/download-artifact@v2
              with:
                  name: zap-report
                  path: ./zap_report
            - name: Commit ZAP Report
              run: |
                  git config --global user.name 'github-actions[bot]'
                  git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                  git add ./zap_report/report.json
                  git commit -m 'Add ZAP report'
                  git push origin HEAD:${{ github.head_ref }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
