name: OWASP ZAP Integration with GitHub Actions

on: [push]

jobs:
    zap_scan:
        runs-on: ubuntu-latest
        name: Scan the web application
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  ref: master
            - name: ZAP Scan
              uses: zaproxy/action-baseline@master
              with:
                  docker_name: "ghcr.io/zaproxy/zaproxy:stable"
                  target: "https://dylane-mu.vercel.app/"
                  rules_file_name: ".zap/rules.tsv"
                  cmd_options: "-a"
            - name: Upload ZAP Scan Report
              uses: actions/upload-artifact@v2
              with:
                  name: zap-scan-report
                  path: ./**/zapReport.md
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Download ZAP Scan Report
              uses: actions/download-artifact@v2
              with:
                  name: zap-scan-report
            - name: Unzip ZAP Scan Report
              run: unzip zap-scan-report.zip
